### ISSUE TITLE
feat: Default to copy syntax for all code blocks that are not in exec shortcut

### ISSUE THREAD

**Issue by Jayclifford345** [grafana/killercoda#26]
Suggestion if possible.  Code blocks should auto-inherit "Copy" privileges unless I override with telling to make it executable.   I.e. in the docs MD, I propose that for "named code blocks" where you're doing triple-backticks and giving it a dialect name (bash, alloy, whatever) -- that the copy START/END directive be optional.  I just can't imagine ever putting a code block in the docs that I don't want to be copyable.

**Comment by jdbaldry** [comment]
Completed in #34
