### ISSUE TITLE
Alloy crashes after a few seconds in Loki Quickstart Demo

### ISSUE THREAD

**Issue by rfratto** [grafana/killercoda#4]
After starting the Docker Compose environment, Alloy crashes after a few seconds of running the `loki.source.docker` component. 

I've tracked this down to a bug in the v1.1.0 release of Alloy. There is a fix available (grafana/alloy#875), but it hasn't been published as a patch release yet.

There are two workarounds I can identify:

* Temporarily pin the Alloy image to `grafana/alloy:v1.0.0` which doesn't have this known issue.
* Temporarily pin the Alloy image to `grafana/alloy-dev:v1.2.0-devel-a30cc8a5a` which is a development build containing the fix.   

If one of the two workarounds above are used, the pin can be removed either when a `v1.1.1` patch release is published with the fix, or when `v1.2` comes out.

**Comment by Jayclifford345** [comment]
Hi @rfratto, 
This is awesome thank you for the update and I will get this fixed!

**Comment by Jayclifford345** [comment]
That's the main repo moved over to alloy-dev for now. I shall leave this issue open to remind myself to put it back on the official release of 1.2.0. Thanks again for letting us know @rfratto !

**Comment by rfratto** [comment]
@Jayclifford345 I just published v1.1.1 with the bugfix today, so this could be updated to that now :)
